<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-29T19:09:39 IST" name="Suite" finished-at="2022-11-29T19:10:02 IST" duration-ms="23448">
    <groups>
    </groups>
    <test started-at="2022-11-29T19:09:39 IST" name="Test" finished-at="2022-11-29T19:10:02 IST" duration-ms="23448">
      <class name="com.community.tests.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.community.tests.LoginTest@6f96c77]" started-at="2022-11-29T19:09:39 IST" name="setUp" finished-at="2022-11-29T19:09:48 IST" duration-ms="9761" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="login()[pri:0, instance:com.community.tests.LoginTest@6f96c77]" started-at="2022-11-29T19:09:48 IST" name="login" finished-at="2022-11-29T19:09:58 IST" duration-ms="9931" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
expected: "Home - Cisco Community"
 but was: "Login to Cisco Community - Cisco Community"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
expected: "Home - Cisco Community"
 but was: "Login to Cisco Community - Cisco Community"
at com.community.tests.LoginTest.login(LoginTest.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.community.tests.LoginTest@6f96c77]" started-at="2022-11-29T19:10:00 IST" name="teardown" finished-at="2022-11-29T19:10:02 IST" duration-ms="2101" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.community.tests.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
